name = "DoseResponse"
uuid = "b75a54f6-5dc4-4d61-8e6c-1ff0e7c207ef"
authors = ["Benjamin Deonovic <bdeonovic@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
